# Generated by Django 5.0.3 on 2024-03-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=200, null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
    ]
